CREATE SCHEMA `CSC350P3` ;

CREATE TABLE `CSC350P3`.`USERS` (
  `USERID` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `STATE` CHAR(2) NOT NULL,
  `ZIPCODE` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`USERID`));
